=== uszkaisandor/xquery-examples/show.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.1">
    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="http://www.w3.org/2001/xml.xsd" />
    
    <xs:element name="show">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="title" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute ref="xml:lang" fixed="en" use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType> 
                </xs:element>
                <xs:element name="imdbURL" type="xs:anyURI"></xs:element>
                <xs:element name="tmdbURL" type="xs:anyURI"></xs:element> 
                <xs:element name="imdbRating" type="ratingType"></xs:element>              
                <xs:element name="mpaaRating" type="xs:token" minOccurs="1" maxOccurs="1"></xs:element>
                <xs:element name="genres" minOccurs="1" maxOccurs="1"> 
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="genre" type="xs:token" minOccurs="1" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="cast" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="role" use="required"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType> 
                </xs:element>
                <xs:element name="seasons" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="season" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>            
                                    <xs:sequence>
                                        <xs:element name="episodes" minOccurs="1" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element ref="episode" minOccurs="1" maxOccurs="unbounded"></xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="number" type="number" use="required"/>                                     
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>    
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    
    <xs:element name="episode">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="title" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
                <xs:element name="airDate" type="xs:date" minOccurs="1" maxOccurs="1"></xs:element>
                <xs:element name="summary" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
                <xs:element name="events" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="event" type="xs:string" minOccurs="1" maxOccurs="unbounded"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="charactersAppearing" minOccurs="1" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="character" type="xs:string" minOccurs="1" maxOccurs="unbounded"></xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="imdbRating" type="ratingType" minOccurs="1" maxOccurs="1"></xs:element>
                <xs:element name="runtime" type="xs:duration"></xs:element>
            </xs:sequence>
            <xs:attribute name="number" type="number" use="required"/>
            <xs:attribute name="id" type="imdbId" use="required"/>
        </xs:complexType>
    </xs:element>
    
    
    <xs:simpleType name="ratingType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="10"/>
            <xs:fractionDigits value="2"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="number">
        <xs:restriction base="xs:nonNegativeInteger">
            <xs:minInclusive value="1"></xs:minInclusive>
        </xs:restriction>
    </xs:simpleType>
    
   
    <xs:simpleType name="imdbId">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{7}"/>
        </xs:restriction>
    </xs:simpleType>
   
</xs:schema>

=== uszkaisandor/xquery-examples/show.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--  Data sources: 
        https://www.imdb.com/title/tt0898266/ 
        https://www.themoviedb.org/tv/1418-the-big-bang-theory?language=en-US 
-->

<show xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="show.xsd">
    <title xml:lang="en">The Big Bang Theory</title>
    <imdbURL>https://www.imdb.com/title/tt0898266/</imdbURL>
    <tmdbURL>https://www.themoviedb.org/tv/1418-the-big-bang-theory</tmdbURL>
    <imdbRating>8.2</imdbRating>
    <mpaaRating>TV-PG</mpaaRating>
    <genres>
        <genre>comedy</genre>
        <genre>romance</genre>
    </genres>
    <cast role="Leonard Hofstadter">Johnny Galecki</cast>
    <cast role="Sheldon Cooper">Jim Parsons</cast>
    <cast role="Penny">Kaley Cuoco</cast>
    <cast role="Howard Wolowitz">Simon Helberg </cast>
    <cast role="Raj Koothrappali">Kunal Nayyar</cast>
    <cast role="Amy Farrah Fowler">Mayim Bialik</cast>
    <cast role="Bernadette Rostenkowski">Melissa Rauch</cast>
    <cast role="Wil Wheaton">Wil Wheaton</cast>
    <cast role="Debbie Wolowitz">Carol Ann Susi</cast>
    <cast role="Stuart Bloom">Kevin Sussman</cast>
    <seasons>
        <season number="1">
            <episodes>
                <episode number="1" id="1091289">
                    <title>Pilot</title>
                    <airDate>2007-09-24</airDate>
                    <summary>Brilliant physicist roommates Leonard and Sheldon meet their new
                        neighbor Penny, who begins showing them that as much as they know about
                        science, they know little about actual living.</summary>
                    <events>
                        <event>Sheldon and Leonard attempt to donate sperm</event>
                        <event>Penny moves in to her apartment across from Leonard and
                            Sheldon</event>
                        <event>Leonard, Sheldon, Howard and Raj meet Penny</event>
                        <event>Main characters introduced</event>
                        <event>Penny showers at Leonard and Sheldon's apartment</event>
                        <event>Sheldon's spot is introduced</event>
                        <event>Howard knows how to say Good Shower in 6 languages</event>
                        <event>Leonard and Sheldon attempt to get Penny's TV back from Kurt, her
                            ex-boyfriend</event>
                        <event>Leonard and Sheldon lose their pants to Kurt</event>
                    </events>
                    <charactersAppearing>
                        <character>Sheldon Cooper</character>
                        <character>Penny</character>
                        <character>Leonard Hofstadter</character>
                        <character>Howard Wolowitz</character>
                        <character>Rajesh Koothrappali</character>
                        <character>Kurt</character>
                        <character>Nurse</character>
                    </charactersAppearing>
                    <imdbRating>8.4</imdbRating>
                    <runtime>P23M</runtime>
                </episode>
                <episode number="2" id="1091289">
                    <title>The Big Bran Hypothesis</title>
                    <airDate>2007-10-01</airDate>
                    <summary>Leonard volunteers to sign for a package in an attempt to make a good
                        impression on Penny, but when he enlists Sheldon for help, his attempt at
                        chivalry goes terribly awry.</summary>
                    <events>
                        <event>Sheldon doesn't understand sarcasm</event>
                        <event>Sheldon sorts his cereal by fiber content</event>
                        <event>Sheldon cleans up Penny's apartment while she sleeps</event>
                        <event>Leonard and Sheldon sign for Penny's furniture delivery</event>
                        <event>Leonard and Sheldon attempt to get Penny's furniture up the
                            stairs</event>
                        <event>They guys start building Penny's media center and then decide it
                            needs to be improved</event>
                    </events>
                    <charactersAppearing>
                        <character>Sheldon Cooper</character>
                        <character>Leonard Hofstadter</character>
                        <character>Howard Wolowitz</character>
                        <character>Rajesh Koothrappali</character>
                        <character>Penny</character>
                    </charactersAppearing>
                    <imdbRating>8.4</imdbRating>
                    <runtime>P21M</runtime>
                </episode>
                <episode number="3" id="1091290">
                    <title>The Fuzzy Boots Corollary</title>
                    <airDate>2007-10-08</airDate>
                    <summary>Leonard asks a woman out after he finds out that Penny is seeing
                        someone.</summary>
                    <events>
                        <event>The guys play a major quest on World of Warcraft</event>
                        <event>Sheldon obtains the Sword of Azeroth</event>
                        <event>Sheldon sells the Sword of Azeroth on Ebay</event>
                        <event>Howard buys the Sword of Azeroth from Sheldon</event>
                        <event>Leonard asks Leslie Winkle out on a date</event>
                        <event>Leonard asks Penny out to dinner implying it's a group dinner</event>
                        <event>Leonard has a panic attack before dinner with Penny</event>
                        <event>Howard and Raj test Sheldon with Asimov's Three Laws of
                            Robotics</event>
                        <event>Leonard hits his head on the table during dinner with Penny</event>
                        <event>Leonard buys cat supplies</event>
                        <event>The guys take dance lessons</event>
                        <event>Leonard sings along to Augustana by Boston</event>
                    </events>
                    <charactersAppearing>
                        <character>Sheldon Cooper</character>
                        <character>Leonard Hofstadter</character>
                        <character>Howard Wolowitz</character>
                        <character>Rajesh Koothrappali</character>
                        <character>Penny</character>
                        <character>Leslie Winkle</character>
                    </charactersAppearing>
                    <imdbRating>7.9</imdbRating>
                    <runtime>P22M</runtime>
                </episode>
                <episode number="4" id="1091291">
                    <title>The Luminous Fish Effect</title>
                    <airDate>2007-10-15</airDate>
                    <summary>Sheldon's getting fired forces him to explore what life has to offer
                        outside physics, leaving Leonard to take drastic action to snap his friend
                        out of his funk.</summary>
                    <events>
                        <event>Party at the University to welcome Dr. Gablehauser</event>
                        <event>Sheldon gets fired for insulting Dr. Gablehauser</event>
                        <event>Howard hires an escort as a date for the party</event>
                        <event>Sheldon experiments with eggs</event>
                        <event>Sheldon and Penny go grocery shopping</event>
                        <event>Sheldon builds a 3d model of DNA for a silicon based lifeform</event>
                        <event>Sheldon's mother visits</event>
                        <event>Sheldon's mother takes him to apologize to Dr. Gablehauser</event>
                        <event>Dr. Gablehauser flirts with Sheldon's mother</event>
                        <event>Sheldon invents glow in the dark goldfish</event>
                        <event>Sheldon's mom tells stories about him as a child</event>
                    </events>
                    <charactersAppearing>
                        <character>Leonard Hofstadter</character>
                        <character>Sheldon Cooper</character>
                        <character>Howard Wolowitz</character>
                        <character>Rajesh Koothrappali</character>
                        <character>Penny</character>
                        <character>Mary Cooper</character>
                        <character>Eric Gablehauser</character>
                    </charactersAppearing>
                    <imdbRating>8.3</imdbRating>
                    <runtime>P21M</runtime>
                </episode>
                <episode number="5" id="1091292">
                    <title>The Hamburger Postulate</title>
                    <airDate>2007-10-22</airDate>
                    <summary>Fearing he's wasting his time on Penny, Leonard ends up making a
                        connection with Leslie.</summary>
                    <events>
                        <event>Civil War re-enactment using condiments</event>
                        <event>Leonard plays the Cello</event>
                        <event>Howard is a human beat box</event>
                        <event>Physic Department String Quartet practices at Leonard and Sheldon's
                            apartment</event>
                        <event>Leslie flirts with Leonard</event>
                        <event>Leslie and Leonard hook up</event>
                        <event>Sheldon doesn't understand the meaning of the tie on the
                            doorknob</event>
                        <event>Leslie fixes the equations on Sheldon's board</event>
                        <event>Leonard tries to figure out what Penny means in her comments about
                            him and Leslie</event>
